baseURL = "https://creative-chaja-132a35.netlify.app/"
title = "Stepner Says"
theme = "PaperMod"

# recommended settings
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  hideAuthor = true
  disableSpecial1stPost = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
